In [72]:
import geopandas as gpd
from shapely.geometry import Point
import pandas as pd
import numpy as np

In [73]:
def parse_dates(date_series):
    for fmt in ('%Y-%m-%d', '%d-%m-%Y', '%d/%m/%Y', '%Y/%m/%d'):
        try:
            return pd.to_datetime(date_series, format=fmt)
        except ValueError:
            continue
    # fallback: let pandas infer
    return pd.to_datetime(date_series, dayfirst=True)

In [74]:
def df_to_gdf(df):
    df["geometry"] = [Point(xy) for xy in zip(df["Longitude"], df["Latitude"])]
    return gpd.GeoDataFrame(df, geometry="geometry", crs="EPSG:4326")

In [75]:
def landsat_map_station(stations_df, landsat_df):
    stations_gdf = df_to_gdf(stations_df)
    landsat_gdf = df_to_gdf(landsat_df)
    
    stations_m = stations_gdf.to_crs(epsg=3857)
    landsat_m  = landsat_gdf.to_crs(epsg=3857)
    stations_unique = stations_m.drop_duplicates(subset=['Latitude', 'Longitude']).reset_index(drop=True)
    
    landsat_to_station = gpd.sjoin_nearest(
        landsat_m, # LEFT: each landsat point
        stations_unique,  # RIGHT: station candidates
        how="left",
        distance_col="dist_m"
    ).groupby(level=0).first()
    
    landsat_to_station["dist_km"] = landsat_to_station["dist_m"] / 1000
    landsat_to_station = landsat_to_station.rename(columns= {'Latitude_left': 'Latitude', 'Longitude_left': 'Longitude', 'Latitude_right': 'Latitude_stations', 'Longitude_right': 'Longitude_stations'})
    
    landsat_to_station['Sample Date'] = parse_dates(landsat_to_station['Sample Date'])
    
    return landsat_to_station

# landsat_to_station.head()

In [76]:
landsat_df.head()

,Latitude,Longitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,_merge_terra,nir,green,swir16,swir22,NDMI,MNDWI,_merge_landsat,Impute_Method,geometry
0,-28.76083,17.73028,2011-01-02,128.912,555.0,10.0,174.2,both,11190.0,11426.0,7687.5,7645.0,0.185538,0.195595,both,Original,POINT (17.73028 -28.76083)
1,-26.86111,28.88472,2011-01-03,74.720,162.9,163.0,124.1,both,17658.5,9550.0,13746.5,10574.0,0.124566,-0.180134,both,Original,POINT (28.88472 -26.86111)
2,-26.45000,28.08583,2011-01-03,89.254,573.0,80.0,127.5,both,15210.0,10720.0,17974.0,14201.0,-0.083293,-0.252805,both,Original,POINT (28.08583 -26.45)
3,-27.67111,27.23694,2011-01-03,82.000,203.6,101.0,129.7,both,14887.0,10943.0,13522.0,11403.0,0.048048,-0.105416,both,Original,POINT (27.23694 -27.67111)
4,-27.35667,27.28639,2011-01-03,56.100,145.1,151.0,129.2,both,16828.5,9502.5,12665.5,9643.0,0.141147,-0.142683,both,Original,POINT (27.28639 -27.35667)

In [77]:
landsat_to_station.head()

,Latitude,Longitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,_merge_terra,nir,green,...,GLC_Managed,GLC_Water,GLC_Aquatic_Veg,GLC_PERC_COV,Popdens_00,Soil_pH,SOC,Soil_wetness,dist_m,dist_km
0,-28.76083,17.73028,2011-01-02,128.912,555.0,10.0,174.2,both,11190.0,11426.0,...,0.12,0.002437,0.0,100.0,16.58,6.99,2.94,17.43,109.909365,0.109909
1,-26.86111,28.88472,2011-01-03,74.720,162.9,163.0,124.1,both,17658.5,9550.0,...,0.63,0.008445,0.0,100.0,76.03,7.35,4.26,56.04,543.377566,0.543378
2,-26.45000,28.08583,2011-01-03,89.254,573.0,80.0,127.5,both,15210.0,10720.0,...,0.09,0.010000,0.0,100.0,1667.67,6.43,3.77,57.57,648.992631,0.648993
3,-27.67111,27.23694,2011-01-03,82.000,203.6,101.0,129.7,both,14887.0,10943.0,...,0.48,0.001115,0.0,100.0,11.24,7.02,3.55,48.13,785.054736,0.785055
4,-27.35667,27.28639,2011-01-03,56.100,145.1,151.0,129.2,both,16828.5,9502.5,...,0.26,0.002343,0.0,100.0,5.28,7.01,3.64,36.12,1097.652078,1.097652

In [78]:
glorich_df.head()

,STAT_ID,Latitude,Longitude,date,Alkalinity,Cl,DIP,SO4,SpecCond25C,pH,Alkalinity_reliability,Cl_reliability,DIP_reliability,SO4_reliability,SpecCond25C_reliability,pH_reliability
0,401569,-28.38,29.01,2015-12-15,1371.704215,209.698814,1.578395,79.4875,16.625249,7.789136,1.0,1.0,1.0,0.4,1.0,1.0
1,401569,-28.38,29.01,2015-12-01,1371.704215,209.698814,1.578395,79.4875,16.625249,7.789136,1.0,1.0,1.0,0.4,1.0,1.0
2,401569,-28.38,29.01,2015-11-15,1371.704215,209.698814,1.578395,79.4875,16.625249,7.789136,1.0,1.0,1.0,0.4,1.0,1.0
3,401569,-28.38,29.01,2015-11-01,1371.704215,209.698814,1.578395,79.4875,16.625249,7.789136,1.0,1.0,1.0,0.4,1.0,1.0
4,401569,-28.38,29.01,2015-10-15,1371.704215,209.698814,1.578395,79.4875,16.625249,7.789136,1.0,1.0,1.0,0.4,1.0,1.0

## Adding hydrochem properties to the station data
This is the dataset with the date and the STAT_ID

In [79]:
def merge_all(glorich_df, landsat_to_station, name):

    glorich_with_date = glorich_df.dropna(subset=['date'])

    # Save original order
    landsat_to_station['_orig_order'] = range(len(landsat_to_station))

    landsat_sorted  = landsat_to_station.sort_values('Sample Date').reset_index(drop=True)
    glorich_sorted  = glorich_with_date.sort_values('date').reset_index(drop=True)

    merged = pd.merge_asof(
        landsat_sorted,
        glorich_sorted,
        left_on='Sample Date',
        right_on='date',
        by='STAT_ID',
        direction='nearest',
        suffixes=('_landsat', '_glorich')
    )
    merged['date_diff_days'] = (
        merged['Sample Date'] - merged['date']
    ).dt.days.abs()
    merged.drop(columns=['index_right', 'Latitude_stations', 'Longitude_stations'], inplace=True)
    merged = merged.rename(columns={'Latitude_landsat': 'Latitude', 'Longitude_landsat': 'Longitude'})

    merged = (
        merged
        .sort_values('SpecCond25C_reliability', ascending=False)
        .drop_duplicates(subset=['Latitude', 'Longitude', 'Sample Date'], keep='first')
    )

    # Restore original row order
    merged = merged.sort_values('_orig_order').reset_index(drop=True)
    merged = merged.drop(columns='_orig_order')

    landsat_ids = set(landsat_sorted['STAT_ID'].unique())
    glorich_ids = set(glorich_with_date['STAT_ID'].unique())

    print("Landsat STAT_IDs:  ", len(landsat_ids))
    print("Glorich STAT_IDs:  ", len(glorich_ids))
    print("Overlapping IDs:   ", len(landsat_ids & glorich_ids))
    print("Merged dataset length:", len(merged))

    merged.to_csv(f'data/{name}_ALL.csv', index=False)

    return merged

## Main coding part

In [80]:
# name = specify training, validation, testing
name = 'training'
stations_df = pd.read_csv('data/stations_with_conditions.csv')
glorich_df = pd.read_csv('data/final_imputed_hydrochem.csv')
glorich_df['date'] = pd.to_datetime(glorich_df['date'], format='%Y-%m-%d')

# just change this to validation / testing set
landsat_df = pd.read_csv('data/train+landsat.csv')

In [81]:
stations_df.head()

,STAT_ID,Latitude,Longitude,geometry,sc,ss,su,mt,va,vb,...,pi,GLC_Artificial,GLC_Managed,GLC_Water,GLC_Aquatic_Veg,GLC_PERC_COV,Popdens_00,Soil_pH,SOC,Soil_wetness
0,400001,-32.31,18.33,POINT (18.33 -32.31),0.0,0.38,0.23,0.0,0.0,0.0,...,0.0,0.0,0.25,0.005508,0.0,100.0,4.75,6.7,3.08,34.46
1,400002,-32.31,18.34,POINT (18.34 -32.31),0.0,0.38,0.23,0.0,0.0,0.0,...,0.0,0.0,0.25,0.005508,0.0,100.0,4.75,6.7,3.08,34.46
2,400003,-32.31,18.34,POINT (18.34 -32.31),0.0,0.38,0.23,0.0,0.0,0.0,...,0.0,0.0,0.25,0.005511,0.0,100.0,4.70,6.7,3.08,34.46
3,400004,-32.31,18.35,POINT (18.35 -32.31),0.0,0.38,0.23,0.0,0.0,0.0,...,0.0,0.0,0.25,0.005511,0.0,100.0,4.70,6.7,3.08,34.46
4,400005,-32.34,18.42,POINT (18.42 -32.34),0.0,0.38,0.22,0.0,0.0,0.0,...,0.0,0.0,0.25,0.002830,0.0,100.0,4.46,6.7,3.12,34.46

In [82]:
stations_df[stations_df['Latitude']== -26.45]

,STAT_ID,Latitude,Longitude,geometry,sc,ss,su,mt,va,vb,...,pi,GLC_Artificial,GLC_Managed,GLC_Water,GLC_Aquatic_Veg,GLC_PERC_COV,Popdens_00,Soil_pH,SOC,Soil_wetness
45,400052,-26.45,29.08,POINT (29.08 -26.45),0.00,0.02,0.0,0.00,0.0,0.97,...,0.0,0.00,0.36,0.00,0.0,100.0,99.33,7.24,4.29,58.64
1103,401468,-26.45,28.08,POINT (28.08 -26.45),0.27,0.29,0.0,0.11,0.0,0.30,...,0.0,0.46,0.09,0.01,0.0,100.0,1667.67,6.43,3.77,57.57
1124,401489,-26.45,28.08,POINT (28.08 -26.45),0.24,0.27,0.0,0.09,0.0,0.38,...,0.0,0.49,0.10,0.01,0.0,100.0,1360.82,6.46,3.78,59.39
1129,401494,-26.45,28.08,POINT (28.08 -26.45),0.27,0.29,0.0,0.11,0.0,0.30,...,0.0,0.46,0.09,0.01,0.0,100.0,1667.67,6.43,3.77,57.57

In [83]:
landsat_to_station = landsat_map_station(stations_df, landsat_df)

In [84]:
merged = merge_all(glorich_df, landsat_to_station, name=name)

Landsat STAT_IDs:   153
Glorich STAT_IDs:   876
Overlapping IDs:    130
Merged dataset length: 9319

In [85]:
merged[merged['Cl'].isna()]

,Latitude,Longitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,_merge_terra,nir,green,...,SO4,SpecCond25C,pH,Alkalinity_reliability,Cl_reliability,DIP_reliability,SO4_reliability,SpecCond25C_reliability,pH_reliability,date_diff_days
2,-26.45000,28.08583,2011-01-03,89.254,573.0,80.0,127.500000,both,15210.0,10720.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,-27.01011,26.69808,2011-01-04,82.200,289.8,192.0,98.600000,both,12433.5,10433.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,-26.98472,26.63228,2011-01-04,196.000,452.0,158.0,98.200005,both,13683.0,10207.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,-28.14194,26.41778,2011-01-04,94.718,227.9,132.0,93.800000,both,14391.0,9840.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,-26.45000,28.08583,2011-01-10,105.711,635.0,80.0,172.900010,both,15210.0,10720.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9305,-26.45000,28.08583,2015-12-21,128.329,718.0,173.0,186.700000,both,15992.5,9962.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9306,-28.40444,30.01306,2015-12-22,69.200,292.0,20.0,181.500000,both,14952.0,10745.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9312,-27.01011,26.69808,2015-12-23,197.855,787.0,183.0,210.000000,both,13467.0,9747.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9316,-26.98472,26.63228,2015-12-23,104.874,835.0,148.0,207.800000,both,14945.0,10732.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9317,-27.93500,26.12667,2015-12-23,128.000,305.0,28.0,222.800000,both,14727.5,11051.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
train_df = pd.read_csv('data/training_ALL.csv')

In [87]:
train_df.shape

(9319, 55)