In [22]:
import geopandas as gpd
from shapely.geometry import Point
import pandas as pd
import numpy as np

In [23]:
def parse_dates(date_series):
    for fmt in ('%Y-%m-%d', '%d-%m-%Y', '%d/%m/%Y', '%Y/%m/%d'):
        try:
            return pd.to_datetime(date_series, format=fmt)
        except ValueError:
            continue
    # fallback: let pandas infer
    return pd.to_datetime(date_series, dayfirst=True)

In [24]:
def df_to_gdf(df):
    df["geometry"] = [Point(xy) for xy in zip(df["Longitude"], df["Latitude"])]
    return gpd.GeoDataFrame(df, geometry="geometry", crs="EPSG:4326")

In [25]:
def landsat_map_station(stations_df, landsat_df):
    stations_gdf = df_to_gdf(stations_df)
    landsat_gdf = df_to_gdf(landsat_df)
    
    stations_m = stations_gdf.to_crs(epsg=3857)
    landsat_m  = landsat_gdf.to_crs(epsg=3857)
    stations_unique = stations_m.drop_duplicates(subset=['Latitude', 'Longitude']).reset_index(drop=True)
    
    landsat_to_station = gpd.sjoin_nearest(
        landsat_m, # LEFT: each landsat point
        stations_unique,  # RIGHT: station candidates
        how="left",
        distance_col="dist_m"
    ).groupby(level=0).first()
    
    landsat_to_station["dist_km"] = landsat_to_station["dist_m"] / 1000
    landsat_to_station = landsat_to_station.rename(columns= {'Latitude_left': 'Latitude', 'Longitude_left': 'Longitude', 'Latitude_right': 'Latitude_stations', 'Longitude_right': 'Longitude_stations'})
    
    landsat_to_station['Sample Date'] = parse_dates(landsat_to_station['Sample Date'])
    
    return landsat_to_station

# landsat_to_station.head()

In [26]:
landsat_df.head()

,Latitude,Longitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,_merge_terra,nir,green,swir16,swir22,NDMI,MNDWI,_merge_landsat,Impute_Method,geometry
0,-34.09639,24.43917,2011-03-09,NaN,NaN,NaN,130.00000,both,12003.0,8511.0,9158.0,8134.5,0.134445,-0.036618,both,Original,POINT (24.43917 -34.09639)
1,-34.09639,24.43917,2011-10-12,NaN,NaN,NaN,152.00000,both,15192.0,8196.0,10225.0,8833.0,0.195420,-0.110146,both,Original,POINT (24.43917 -34.09639)
2,-34.09639,24.43917,2011-11-08,NaN,NaN,NaN,152.00000,both,14338.5,8332.0,10467.5,8750.0,0.156051,-0.113593,both,Original,POINT (24.43917 -34.09639)
3,-34.09639,24.43917,2012-02-07,NaN,NaN,NaN,130.00000,both,14411.0,8184.0,10236.0,8420.0,0.169392,-0.111401,both,Original,POINT (24.43917 -34.09639)
4,-34.09639,24.43917,2013-02-26,NaN,NaN,NaN,135.40001,both,14697.0,8345.0,10882.0,8734.0,0.149146,-0.131950,both,Original,POINT (24.43917 -34.09639)

In [27]:
landsat_to_station.head()

,Latitude,Longitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,_merge_terra,nir,green,...,GLC_Water,GLC_Aquatic_Veg,GLC_PERC_COV,Popdens_00,Soil_pH,SOC,Soil_wetness,dist_m,dist_km,_orig_order
0,-34.09639,24.43917,2011-03-09,NaN,NaN,NaN,130.00000,both,12003.0,8511.0,...,0.0,0.0,100.0,4.93,6.62,3.75,89.41,49211.661255,49.211661,0
1,-34.09639,24.43917,2011-10-12,NaN,NaN,NaN,152.00000,both,15192.0,8196.0,...,0.0,0.0,100.0,4.93,6.62,3.75,89.41,49211.661255,49.211661,1
2,-34.09639,24.43917,2011-11-08,NaN,NaN,NaN,152.00000,both,14338.5,8332.0,...,0.0,0.0,100.0,4.93,6.62,3.75,89.41,49211.661255,49.211661,2
3,-34.09639,24.43917,2012-02-07,NaN,NaN,NaN,130.00000,both,14411.0,8184.0,...,0.0,0.0,100.0,4.93,6.62,3.75,89.41,49211.661255,49.211661,3
4,-34.09639,24.43917,2013-02-26,NaN,NaN,NaN,135.40001,both,14697.0,8345.0,...,0.0,0.0,100.0,4.93,6.62,3.75,89.41,49211.661255,49.211661,4

In [28]:
glorich_df.head()

,STAT_ID,Latitude,Longitude,date,Alkalinity,Cl,DIP,SO4,SpecCond25C,pH,Alkalinity_reliability,Cl_reliability,DIP_reliability,SO4_reliability,SpecCond25C_reliability,pH_reliability
0,401569,-28.38,29.01,2015-12-15,1371.704215,209.698814,1.578395,79.4875,16.625249,7.789136,1.0,1.0,1.0,0.4,1.0,1.0
1,401569,-28.38,29.01,2015-12-01,1371.704215,209.698814,1.578395,79.4875,16.625249,7.789136,1.0,1.0,1.0,0.4,1.0,1.0
2,401569,-28.38,29.01,2015-11-15,1371.704215,209.698814,1.578395,79.4875,16.625249,7.789136,1.0,1.0,1.0,0.4,1.0,1.0
3,401569,-28.38,29.01,2015-11-01,1371.704215,209.698814,1.578395,79.4875,16.625249,7.789136,1.0,1.0,1.0,0.4,1.0,1.0
4,401569,-28.38,29.01,2015-10-15,1371.704215,209.698814,1.578395,79.4875,16.625249,7.789136,1.0,1.0,1.0,0.4,1.0,1.0

## Adding hydrochem properties to the station data
This is the dataset with the date and the STAT_ID

In [29]:
def merge_all(glorich_df, landsat_to_station, name):

    glorich_with_date = glorich_df.dropna(subset=['date'])

    # Save original order
    landsat_to_station['_orig_order'] = range(len(landsat_to_station))

    landsat_sorted  = landsat_to_station.sort_values('Sample Date').reset_index(drop=True)
    glorich_sorted  = glorich_with_date.sort_values('date').reset_index(drop=True)

    merged = pd.merge_asof(
        landsat_sorted,
        glorich_sorted,
        left_on='Sample Date',
        right_on='date',
        by='STAT_ID',
        direction='nearest',
        suffixes=('_landsat', '_glorich')
    )
    merged['date_diff_days'] = (
        merged['Sample Date'] - merged['date']
    ).dt.days.abs()
    merged.drop(columns=['index_right', 'Latitude_stations', 'Longitude_stations'], inplace=True)
    merged = merged.rename(columns={'Latitude_landsat': 'Latitude', 'Longitude_landsat': 'Longitude'})

    merged = (
        merged
        .sort_values('SpecCond25C_reliability', ascending=False)
        .drop_duplicates(subset=['Latitude', 'Longitude', 'Sample Date'], keep='first')
    )

    # Restore original row order
    merged = merged.sort_values('_orig_order').reset_index(drop=True)
    merged = merged.drop(columns='_orig_order')

    landsat_ids = set(landsat_sorted['STAT_ID'].unique())
    glorich_ids = set(glorich_with_date['STAT_ID'].unique())

    print("Landsat STAT_IDs:  ", len(landsat_ids))
    print("Glorich STAT_IDs:  ", len(glorich_ids))
    print("Overlapping IDs:   ", len(landsat_ids & glorich_ids))
    print("Merged dataset length:", len(merged))

    merged.to_csv(f'data/{name}_ALL.csv', index=False)

    return merged

## Main coding part

In [30]:
# name = specify training, validation, testing
name = 'testing'
stations_df = pd.read_csv('data/stations_with_conditions.csv')
glorich_df = pd.read_csv('data/final_imputed_hydrochem.csv')
glorich_df['date'] = pd.to_datetime(glorich_df['date'], format='%Y-%m-%d')

# just change this to validation / testing set
landsat_df = pd.read_csv('data/test+landsat.csv')

In [31]:
stations_df.head()

,STAT_ID,Latitude,Longitude,geometry,sc,ss,su,mt,va,vb,...,pi,GLC_Artificial,GLC_Managed,GLC_Water,GLC_Aquatic_Veg,GLC_PERC_COV,Popdens_00,Soil_pH,SOC,Soil_wetness
0,400001,-32.31,18.33,POINT (18.33 -32.31),0.0,0.38,0.23,0.0,0.0,0.0,...,0.0,0.0,0.25,0.005508,0.0,100.0,4.75,6.7,3.08,34.46
1,400002,-32.31,18.34,POINT (18.34 -32.31),0.0,0.38,0.23,0.0,0.0,0.0,...,0.0,0.0,0.25,0.005508,0.0,100.0,4.75,6.7,3.08,34.46
2,400003,-32.31,18.34,POINT (18.34 -32.31),0.0,0.38,0.23,0.0,0.0,0.0,...,0.0,0.0,0.25,0.005511,0.0,100.0,4.70,6.7,3.08,34.46
3,400004,-32.31,18.35,POINT (18.35 -32.31),0.0,0.38,0.23,0.0,0.0,0.0,...,0.0,0.0,0.25,0.005511,0.0,100.0,4.70,6.7,3.08,34.46
4,400005,-32.34,18.42,POINT (18.42 -32.34),0.0,0.38,0.22,0.0,0.0,0.0,...,0.0,0.0,0.25,0.002830,0.0,100.0,4.46,6.7,3.12,34.46

In [32]:
stations_df[stations_df['Latitude']== -26.45]

,STAT_ID,Latitude,Longitude,geometry,sc,ss,su,mt,va,vb,...,pi,GLC_Artificial,GLC_Managed,GLC_Water,GLC_Aquatic_Veg,GLC_PERC_COV,Popdens_00,Soil_pH,SOC,Soil_wetness
45,400052,-26.45,29.08,POINT (29.08 -26.45),0.00,0.02,0.0,0.00,0.0,0.97,...,0.0,0.00,0.36,0.00,0.0,100.0,99.33,7.24,4.29,58.64
1103,401468,-26.45,28.08,POINT (28.08 -26.45),0.27,0.29,0.0,0.11,0.0,0.30,...,0.0,0.46,0.09,0.01,0.0,100.0,1667.67,6.43,3.77,57.57
1124,401489,-26.45,28.08,POINT (28.08 -26.45),0.24,0.27,0.0,0.09,0.0,0.38,...,0.0,0.49,0.10,0.01,0.0,100.0,1360.82,6.46,3.78,59.39
1129,401494,-26.45,28.08,POINT (28.08 -26.45),0.27,0.29,0.0,0.11,0.0,0.30,...,0.0,0.46,0.09,0.01,0.0,100.0,1667.67,6.43,3.77,57.57

In [33]:
landsat_to_station = landsat_map_station(stations_df, landsat_df)

In [34]:
merged = merge_all(glorich_df, landsat_to_station, name=name)

Landsat STAT_IDs:   23
Glorich STAT_IDs:   876
Overlapping IDs:    21
Merged dataset length: 200

In [35]:
merged[merged['Cl'].isna()]

,Latitude,Longitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,pet,_merge_terra,nir,green,...,SO4,SpecCond25C,pH,Alkalinity_reliability,Cl_reliability,DIP_reliability,SO4_reliability,SpecCond25C_reliability,pH_reliability,date_diff_days
4,-32.00056,28.58167,2014-10-01,NaN,NaN,NaN,152.500000,both,9125.0,11100.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,-32.00056,28.58167,2014-09-03,NaN,NaN,NaN,152.500000,both,9534.0,11336.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,-32.00056,28.58167,2014-08-06,NaN,NaN,NaN,152.500000,both,8884.5,10063.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,-33.18536,27.39075,2011-09-22,NaN,NaN,NaN,161.400010,both,16004.0,10236.0,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,7.0
12,-32.00056,28.58167,2012-11-21,NaN,NaN,NaN,144.500000,both,12623.0,11073.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,-32.00056,28.58167,2014-07-09,NaN,NaN,NaN,152.500000,both,9338.5,10082.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,-32.00056,28.58167,2014-06-04,NaN,NaN,NaN,129.100000,both,8823.5,10519.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,-33.18536,27.39075,2015-07-02,NaN,NaN,NaN,161.900010,both,16567.5,9081.5,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,1.0
29,-33.18536,27.39075,2012-05-31,NaN,NaN,NaN,136.400010,both,13943.0,9666.0,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,1.0
40,-31.90306,25.48222,2014-05-19,NaN,NaN,NaN,187.900010,both,13404.5,9492.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,-33.18536,27.39075,2015-11-18,NaN,NaN,NaN,161.900010,both,20018.0,9304.0,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,3.0
49,-32.00056,28.58167,2014-10-29,NaN,NaN,NaN,152.500000,both,11417.5,12053.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,-33.18536,27.39075,2013-10-21,NaN,NaN,NaN,165.200000,both,18905.5,9320.0,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,6.0
61,-32.00056,28.58167,2013-05-08,NaN,NaN,NaN,126.100000,both,11016.0,10945.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,-31.90306,25.48222,2011-03-08,NaN,NaN,NaN,188.700000,both,14525.5,9294.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,-33.18536,27.39075,2015-01-16,NaN,NaN,NaN,161.900010,both,20077.0,9791.5,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,1.0
103,-32.00056,28.58167,2014-04-09,NaN,NaN,NaN,129.100000,both,10256.5,10433.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,-32.00056,28.58167,2011-07-06,NaN,NaN,NaN,127.200005,both,10754.0,11229.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,-33.18536,27.39075,2015-09-28,NaN,NaN,NaN,161.900010,both,15967.0,9733.0,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,3.0
118,-33.18536,27.39075,2014-07-22,NaN,NaN,NaN,159.400010,both,16256.5,8912.5,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,7.0
124,-33.18536,27.39075,2015-10-29,NaN,NaN,NaN,161.900010,both,20018.0,9304.0,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,3.0
128,-31.90306,25.48222,2012-04-25,NaN,NaN,NaN,173.300000,both,13893.0,9273.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,-33.18536,27.39075,2012-09-20,NaN,NaN,NaN,153.400010,both,16193.0,9405.0,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,5.0
158,-33.18536,27.39075,2012-06-28,NaN,NaN,NaN,136.400010,both,13564.0,8843.0,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,3.0
161,-31.90306,25.48222,2012-12-03,NaN,NaN,NaN,209.200000,both,16465.5,10506.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,-33.18536,27.39075,2014-07-10,NaN,NaN,NaN,159.400010,both,16796.0,9058.5,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,5.0
180,-33.18536,27.39075,2012-12-04,NaN,NaN,NaN,153.400010,both,17771.0,9804.0,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,3.0
181,-33.18536,27.39075,2012-11-15,NaN,NaN,NaN,153.400010,both,17771.0,9804.0,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,0.0
183,-32.00056,28.58167,2011-01-19,NaN,NaN,NaN,127.200005,both,13279.5,11389.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,-33.18536,27.39075,2014-09-04,NaN,NaN,NaN,159.400010,both,15883.0,9083.5,...,NaN,35.058824,7.878235,NaN,NaN,1.0,NaN,1.0,1.0,3.0

In [36]:
train_df = pd.read_csv('data/training_ALL.csv')

In [37]:
train_df.shape

(9319, 55)